name: Build and push to Cloudfront on dev stage

on:
  push:
    branches: [main]

jobs:
  deploy-cloudfront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-source-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-source-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Create env
        run: |
          echo "VITE_APP_VERSION=${{ secrets.VITE_APP_VERSION }}" >> .env
          echo "VITE_GOOGLE_API_KEY=${{ secrets.VITE_GOOGLE_API_KEY }}" >> .env
          echo "VITE_DOCUMENT_ENDPOINT=${{ secrets.VITE_DOCUMENT_ENDPOINT }}" >> .env

      - name: Install dependencies
        run: yarn --cache-folder ~/.yarn --frozen-lockfile --check-files

      - name: Build source
        run: yarn build

      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          target: argon-dashboard-vue3
          channelId: live
          projectId: ltv-project-template
          entryPoint: ./

      - name: S3 and CloudFront Deploy
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
